version: '3.1'

services:

  bot:
    # prod
    #image: egregors/vldc_bot:latest
    # dev
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mongo
    env_file:
      - ./.env

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
