name: Pull requests Lint/Test

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8 and type check with mypy
      run: |
        pip install flake8 mypy
        make lint
    - name: Test with pytest
      run: |
        pip install pytest
        export PYTHONPATH=./bot && pytest
